version: '3.8'

networks:
  app-network:

volumes:
  app-data:
  mysql-database:
    driver: local


services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:

  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      app-network:
    
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpasswordmysql
    volumes:
      - mysql-database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      app-network:

